version: "3"

services:
  postgres:
    container_name: lovelace-db
    image: postgres:12
    ports:
      - 127.0.0.1:5432:5432
    hostname: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
